version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 8000:80
    depends_on:
      - api
  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    environment:
      DB_HOST: postgres
    volumes:
      - ./docker_config.py:/code/default_config.py
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
    volumes:
      - ./docker_config.py:/code/default_config.py
    command: sleep 5 && python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist-postgres
      POSTGRES_HOST: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432






