version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build:
      context: .
    environment:
      DB_HOST: postgres
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.docker_env:/api/.env
  migrations:
    build:
      context: .
    environment:
      DB_HOST: postgres
      HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker_env:/api/.env
    command: python manage.py migrate
  bot:
    build:
      context: .
    environment:
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_HOST: postgres
      SOCIAL_AUTH_VK_OAUTH2_KEY: $SOCIAL_AUTH_VK_OAUTH2_KEY
      SOCIAL_AUTH_VK_OAUTH2_SECRET: $SOCIAL_AUTH_VK_OAUTH2_SECRET
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    command: python manage.py runbot

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_HOST: $DB_HOST
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todolist"]
      interval: 5s
      timeout: 5s
      retries: 15
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 700