version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
  api:
    image: vladapython/todolist
    environment:
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_HOST: postgres
    ports:
      - "8000:8000"
    volumes:
      - ./.docker_env:/api/.env
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    image: vladapython/todolist
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
    volumes:
      - ./.docker_env:/api/.env
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_HOST: $DB_HOST
    volumes:
      - ./postgres_data:/var/lib/postgresql/data 700
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todolist"]
      interval: 5s
      timeout: 5s
      retries: 5
