# Generated by Django 4.0.1 on 2023-03-19 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0002_tguser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'tg пользователь', 'verbose_name_plural': 'tg пользователи'},
        ),
        migrations.RenameField(
            model_name='tguser',
            old_name='chat_id',
            new_name='tg_id',
        ),
        migrations.AddField(
            model_name='tguser',
            name='tg_chat_id',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(default=None, max_length=35),
        ),
    ]
