# Generated by Django 4.0.1 on 2023-03-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_tguser_tg_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='tg_id',
        ),
    ]
