# Generated by Django 4.0.1 on 2023-03-28 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_tguser_chat_id_alter_tguser_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='username',
        ),
    ]
